version: '3.8'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: "python:3.9-slim"
    volumes:
      - ./data:/data